input_h: &h 18
input_w: &w 32
patch_size: 2
in_channels: &c 16
hidden_size: 1024
depth: 16
num_heads: 16
mlp_ratio: 4.0
stride: 4
max_frames: 8
precision: bf16-mixed
gradient_checkpointing: true
observation_shape: [*c, *h, *w]